name = "Completa"
author = "Gael Lopez"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fc63a9bc0e7b406c9fc142ee67b8da7ede2c81a30b982b563746a85f474b587"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
