name = "Completa"
author = "Gael Lopez"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5eb517c21bf934df1e4c91cf4cdadc8a1b3ba92450f1678dc7593a9ace65bb14"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
