name = "Completa"
author = "Gael Lopez"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aadb28a521865ad5b522a5e60d4b93cd872576320792bb8c4259675fa4b39748"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
