name = "Lite"
author = "Gael Lopez"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b799d3f1d717ca96c37fdd913f94f3e5d742ebcb0d73604f28529e696679184d"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
