name = "Lite"
author = "Gael Lopez"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34416275780f1e08404fcfa75782e443ed9b23cedf25bfa8832c37191dc702fc"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
