name = "Completa"
author = "Gael Lopez"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1aafd2ad76abc283cd5111be60a7ab7ff27f38cae045e552d678d7483ce908e"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
